### ISSUE TITLE
Which mothod for 2D landmarks prediction?

### ISSUE THREAD

**Issue by weihaosky** [xg-chu/GAGAvatar_track#1]
Thanks for this excellent work!
The VGGHeads seems not to predict 2D landmarks. May I ask which method do you use to predict the 2D landmarks?
Many thanks!

**Comment by xg-chu** [comment]
We used the HRNet-based model developed by Xiaobing for 2D landmarks prediction, the VGGHead itself does not predict 2D landmarks.
